config/routes.rb
Rails.application.routes.draw do
  resources :dicas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dica.rb
class Dica < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dicas_controller.rb
class DicasController < ApplicationController
  before_action :set_dica, only: %i[ show edit update destroy ]

  # GET /dicas or /dicas.json
  def index
    @dicas = Dica.all
  end

  # GET /dicas/1 or /dicas/1.json
  def show
  end

  # GET /dicas/new
  def new
    @dica = Dica.new
  end

  # GET /dicas/1/edit
  def edit
  end

  # POST /dicas or /dicas.json
  def create
    @dica = Dica.new(dica_params)

    respond_to do |format|
      if @dica.save
        format.html { redirect_to dica_url(@dica), notice: "Dica was successfully created." }
        format.json { render :show, status: :created, location: @dica }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dicas/1 or /dicas/1.json
  def update
    respond_to do |format|
      if @dica.update(dica_params)
        format.html { redirect_to dica_url(@dica), notice: "Dica was successfully updated." }
        format.json { render :show, status: :ok, location: @dica }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dicas/1 or /dicas/1.json
  def destroy
    @dica.destroy

    respond_to do |format|
      format.html { redirect_to dicas_url, notice: "Dica was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dica
      @dica = Dica.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dica_params
      params.require(:dica).permit(:titulo, :genero, :descricao, :nota)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dicas_helper.rb
module DicasHelper
end

app/views/dicas/_dica.html.erb
<div id="<%= dom_id dica %>">
  <p>
    <strong>Titulo:</strong>
    <%= dica.titulo %>
  </p>

  <p>
    <strong>Genero:</strong>
    <%= dica.genero %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= dica.descricao %>
  </p>

  <p>
    <strong>Nota:</strong>
    <%= dica.nota %>
  </p>

</div>

app/views/dicas/_form.html.erb
<%= form_with(model: dica) do |form| %>
  <% if dica.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dica.errors.count, "error") %> prohibited this dica from being saved:</h2>

      <ul>
        <% dica.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :genero, style: "display: block" %>
    <%= form.text_field :genero %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.label :nota, style: "display: block" %>
    <%= form.text_field :nota %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dicas/edit.html.erb
<h1>Editing dica</h1>

<%= render "form", dica: @dica %>

<br>

<div>
  <%= link_to "Show this dica", @dica %> |
  <%= link_to "Back to dicas", dicas_path %>
</div>

app/views/dicas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dicas de Filmes bons que vi</h1>

<div id="dicas">
  <% @dicas.each do |dica| %>
    <%= render dica %>
    <p>
      <%= link_to "Show this dica", dica %>
    </p>
  <% end %>
</div>

<%= link_to "New dica", new_dica_path %>

app/views/dicas/new.html.erb
<h1>New dica</h1>

<%= render "form", dica: @dica %>

<br>

<div>
  <%= link_to "Back to dicas", dicas_path %>
</div>

app/views/dicas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dica %>

<div>
  <%= link_to "Edit this dica", edit_dica_path(@dica) %> |
  <%= link_to "Back to dicas", dicas_path %>

  <%= button_to "Destroy this dica", @dica, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filmes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>